{% set name = "sqlacodegen" %}
{% set version = "3.0.0b2" %}
{% set sha256 = "9976f36b04416877990436426b7f76cc905ad96b1ed92d1780c6432474d0a57d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - sqlacodegen = sqlacodegen.cli:main

requirements:
  host:
    - python
    - pip
    - setuptools  >=42
    - setuptools_scm  >=3.4

  run:
    - python
    - dataclasses  # [py<37]
    - importlib_metadata  # [py<38]
    - inflect >=4.0.0
    - sqlalchemy >=1.3.0

test:
  imports:
    - sqlacodegen
  commands:
    - sqlacodegen --help

about:
  home: http://pypi.python.org/pypi/sqlacodegen/
  license: MIT
  license_file: LICENSE
  summary: Automatic model code generator for SQLAlchemy
  license_family: MIT

extra:
  recipe-maintainers:
    - rzillman
    - dhirschfeld
