{% set name = "sqlacodegen" %}
{% set version = "3.0.0" %}
{% set sha256 = "785bc9307b787a9ae7ffc1460abf0a718862b6fa47f304259503612298e523f2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - sqlacodegen = sqlacodegen.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=64
    - setuptools_scm >=6.4
  run:
    - python >={{ python_min }}
    - importlib-metadata
    - inflect >=4.0.0
    - sqlalchemy >=2.0.23
  run_constrained:
    - geoalchemy2 >=0.11.1
    - sqlmodel >=0.0.22
    - sqlalchemy-citext >=1.7.0
    - pgvector >=0.2.4

test:
  requires:
    - python {{ python_min }}
  imports:
    - sqlacodegen
  commands:
    - sqlacodegen --help

about:
  home: http://pypi.python.org/pypi/sqlacodegen/
  license: MIT
  license_file: LICENSE
  summary: Automatic model code generator for SQLAlchemy
  license_family: MIT

extra:
  recipe-maintainers:
    - rzillman
    - dhirschfeld
